# Generated by Django 3.0.14 on 2024-10-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('class_name', models.CharField(max_length=50)),
                ('speciality', models.CharField(choices=[('GL', 'Génie Logiciel'), ('DS', 'Data Science'), ('RC', 'Réseau et Cloud')], max_length=2)),
                ('photo', models.ImageField(upload_to='student_photos/')),
                ('authorized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
